name: Greeting from ChenChang
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Chang
        LAST_NAME: CHEN
      run: |
        echo $MY_VAR $FIRST_NAME $LAST_NAME.
    
